//<editor-fold defaultstate="collapsed" desc=" COPYRIGHT AND LICENSE ">
/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
University of Warsaw, Interdisciplinary Centre for Mathematical and
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */
//</editor-fold>

package pl.edu.icm.visnow.lib.basic.testdata.VNLogo;



/**
 *
 ** @author Krzysztof S. Nowinski, University of Warsaw ICM
 */
public class GUI extends javax.swing.JPanel
{
   private Params params;

   /** Creates new form GUI */
   public GUI()
   {
      initComponents();
   }

   public void setParams(Params params)
   {
      this.params = params;
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sizeSlider = new pl.edu.icm.visnow.gui.widgets.ExtendedSlider();
        aspectSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
        widthSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
        distanceSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setLayout(new java.awt.GridBagLayout());

        sizeSlider.setScaleType(pl.edu.icm.visnow.gui.widgets.ExtendedSlider.ScaleType.LOGARITHMIC);
        sizeSlider.setShowingFields(false);
        sizeSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("detail level"));
        sizeSlider.setMax(10000.0F);
        sizeSlider.setMin(10.0F);
        sizeSlider.setName("sizeSlider"); // NOI18N
        sizeSlider.setVal(100.0F);
        sizeSlider.setVerifyInputWhenFocusTarget(false);
        sizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(sizeSlider, gridBagConstraints);

        aspectSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("aspect"));
        aspectSlider.setName("aspectSlider"); // NOI18N
        aspectSlider.setShowingFields(false);
        aspectSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aspectSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(aspectSlider, gridBagConstraints);

        widthSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("ribbon width"));
        widthSlider.setName("widthSlider"); // NOI18N
        widthSlider.setShowingFields(false);
        widthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                widthSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(widthSlider, gridBagConstraints);

        distanceSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("ribbon distance"));
        distanceSlider.setName("distanceSlider"); // NOI18N
        distanceSlider.setShowingFields(false);
        distanceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                distanceSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(distanceSlider, gridBagConstraints);

        filler1.setName("filler1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weighty = 1.0;
        add(filler1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

   private void sizeSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sizeSliderStateChanged
   {//GEN-HEADEREND:event_sizeSliderStateChanged
      if (params != null && !sizeSlider.isAdjusting())
         params.setNPoints((int)sizeSlider.getVal());
   }//GEN-LAST:event_sizeSliderStateChanged

   private void aspectSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_aspectSliderStateChanged
   {//GEN-HEADEREND:event_aspectSliderStateChanged
      params.setAdjusting(true);
      params.setAspect(aspectSlider.getVal());
   }//GEN-LAST:event_aspectSliderStateChanged

   private void distanceSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_distanceSliderStateChanged
   {//GEN-HEADEREND:event_distanceSliderStateChanged
       params.setAdjusting(true);
       params.setDistance(distanceSlider.getVal());
   }//GEN-LAST:event_distanceSliderStateChanged

   private void widthSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_widthSliderStateChanged
   {//GEN-HEADEREND:event_widthSliderStateChanged
       params.setAdjusting(true);
       params.setWidth(widthSlider.getVal());
   }//GEN-LAST:event_widthSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.edu.icm.visnow.gui.widgets.FloatSlider aspectSlider;
    private pl.edu.icm.visnow.gui.widgets.FloatSlider distanceSlider;
    private javax.swing.Box.Filler filler1;
    private pl.edu.icm.visnow.gui.widgets.ExtendedSlider sizeSlider;
    private pl.edu.icm.visnow.gui.widgets.FloatSlider widthSlider;
    // End of variables declaration//GEN-END:variables
}
