/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.filters.IntensityEqualizer;

import java.awt.GridBagConstraints;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import pl.edu.icm.visnow.datasets.RegularField;

/**
 * @author  Bartosz Borucki (babor@icm.edu.pl)
 * Warsaw University, Interdisciplinary Centre
 * for Mathematical and Computational Modelling
 */
public class GUI extends javax.swing.JPanel {
    private Params params = new Params();
    
    /** Creates new form GUI */
    public GUI() {
        initComponents();
        updateGUI();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        holdButton = new javax.swing.JToggleButton();
        fullPaddingCB = new javax.swing.JCheckBox();
        gainPanel = new javax.swing.JPanel();
        gainSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
        weightsPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        holdButton.setText("Hold");
        holdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(holdButton, gridBagConstraints);

        fullPaddingCB.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        fullPaddingCB.setText("use full padding");
        fullPaddingCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullPaddingCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        add(fullPaddingCB, gridBagConstraints);

        gainPanel.setMinimumSize(new java.awt.Dimension(200, 70));
        gainPanel.setPreferredSize(new java.awt.Dimension(200, 70));
        gainPanel.setLayout(new java.awt.BorderLayout());

        gainSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "global gain", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        gainSlider.setMax(2.0F);
        gainSlider.setMin(-2.0F);
        gainSlider.setShowingFields(false);
        gainSlider.setVal(1.0F);
        gainSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gainSliderStateChanged(evt);
            }
        });
        gainPanel.add(gainSlider, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(gainPanel, gridBagConstraints);

        weightsPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(weightsPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void holdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonActionPerformed
        params.setSilent(holdButton.isSelected());
    }//GEN-LAST:event_holdButtonActionPerformed

    private void gainSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gainSliderStateChanged
        if(gainSlider.getVal() != params.getGain() && !gainSlider.isAdjusting())
            params.setGain(gainSlider.getVal());

    }//GEN-LAST:event_gainSliderStateChanged

    private void fullPaddingCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullPaddingCBActionPerformed
        params.setFullPadding(fullPaddingCB.isSelected());
    }//GEN-LAST:event_fullPaddingCBActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox fullPaddingCB;
    private javax.swing.JPanel gainPanel;
    private pl.edu.icm.visnow.gui.widgets.FloatSlider gainSlider;
    private javax.swing.JToggleButton holdButton;
    private javax.swing.JPanel weightsPanel;
    // End of variables declaration//GEN-END:variables

    public void setParams(Params params) {
        this.params = params;
        params.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                updateGUI();
            }
        });
        updateGUI();
    }


    private WeightUI[] wuis = null;

    public void recreateGUI() {
        weightsPanel.removeAll();
        wuis = null;

        if(params == null) {
            return;
        }

        if(params.getWeights() == null) {
            return;
        }

        

        float[] weights = params.getWeights();
        wuis = new WeightUI[weights.length];
        for (int i = 0; i < weights.length; i++) {
            wuis[i] = new WeightUI();
            wuis[i].setParams(params);
            wuis[i].setWeightIndex(i);

            GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = i;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints.weightx = 1.0;
            if(i == weights.length - 1)
                gridBagConstraints.weighty = 1.0;
            weightsPanel.add(wuis[i], gridBagConstraints);
        }
        revalidate();
        repaint();
    }

    private void updateGUI() {
        if(params == null)
            return;

        fullPaddingCB.setSelected(params.isFullPadding());

        gainSlider.setVal(params.getGain());

        if(params.getWeights() == null)
            return;

        if(wuis == null)
            return;

        for (int i = 0; i < wuis.length; i++) {
            wuis[i].updateGUI();
        }
    }

}
