/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.filters.IntensityEqualizer;

/**
 *
 * @author babor
 */
public class WeightUI extends javax.swing.JPanel {

    /** Creates new form WeightUI */
    public WeightUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        weightSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();

        setMinimumSize(new java.awt.Dimension(200, 60));
        setPreferredSize(new java.awt.Dimension(200, 60));
        setLayout(new java.awt.GridBagLayout());

        weightSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "weight", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        weightSlider.setMax(2.0F);
        weightSlider.setMin(-2.0F);
        weightSlider.setName("weightSlider"); // NOI18N
        weightSlider.setShowingFields(false);
        weightSlider.setVal(1.0F);
        weightSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                weightSliderMouseReleased(evt);
            }
        });
        weightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                weightSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(weightSlider, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void weightSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightSliderMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_weightSliderMouseReleased

    private void weightSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_weightSliderStateChanged
        if(weightSlider.getVal() != params.getWeight(this.weightIndex) && !weightSlider.isAdjusting())
            params.setWeight(this.weightIndex, weightSlider.getVal());
    }//GEN-LAST:event_weightSliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.edu.icm.visnow.gui.widgets.FloatSlider weightSlider;
    // End of variables declaration//GEN-END:variables

    
    private int weightIndex = 0;
    private Params params = null;
    
    public void setParams(Params p) {
        this.params = p;
    }
    
    public void setWeightIndex(int n) {
        this.weightIndex = n;
        weightSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Level "+n+" weight", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10)));
        updateGUI();
    }

    public void updateGUI() {
        if(params == null) {
            weightSlider.setEnabled(false);
            return;
        }

        weightSlider.setEnabled(true);
        weightSlider.setVal(params.getWeight(this.weightIndex));
    }



}
