/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.filters.AddMargins;

import pl.edu.icm.visnow.datasets.Field;
import pl.edu.icm.visnow.lib.basic.filters.AddMargins.TextFieldCellEditor.TextFieldCell;
import pl.edu.icm.visnow.lib.basic.filters.AddMargins.TextFieldCellEditor.TextFieldCellEditor;
import pl.edu.icm.visnow.lib.utils.PaddingType;


public class GUI extends javax.swing.JPanel {

   protected Params params;

   /**
    * Set the value of params
    *
    * @param params new value of params
    */
   public void setParams(Params params)
   {
      this.params = params;
   }
    /** Creates new form EmptyVisnowModuleGUI */
    public GUI() {
        initComponents();
        marginsTable.setDefaultEditor(Integer.class, new TextFieldCellEditor(new TextFieldCell(marginsTable), Integer.class));
    }
    
    private void update()
    {
       int[][] m = new int[3][2];
       for (int i = 0; i < 3; i++)
          for (int j = 0; j < 2; j++)
          {
             m[i][j] = (Integer)marginsTable.getValueAt(i, j + 1);
             /* Keeps from changing values to negative ones! */
             if (m[i][j] < 0)
             {
                 marginsTable.setValueAt((Integer) 0, i, j + 1);
                 m[i][j] = 0;
             }
          }
       params.setMargins(m);
       params.setComponents(dataComponentList.getSelectedComponents());
       if (zeroButton.isSelected()) params.setMethod(PaddingType.ZERO);
       if (fixedButton.isSelected()) params.setMethod(PaddingType.FIXED);
       if (periodicButton.isSelected()) params.setMethod(PaddingType.PERIODIC);
       if (reflectedButton.isSelected()) params.setMethod(PaddingType.REFLECTED);
    }

    private void fireStateChanged()
    {
        params.fireStateChanged();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbMargins = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        marginsTable = new javax.swing.JTable();
        runButton = new javax.swing.JButton();
        dataComponentList = new pl.edu.icm.visnow.lib.gui.DataComponentList();
        zeroButton = new javax.swing.JRadioButton();
        fixedButton = new javax.swing.JRadioButton();
        periodicButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reflectedButton = new javax.swing.JRadioButton();

        lbMargins.setText("Margins:");

        marginsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"x",  new Integer(1),  new Integer(1)},
                {"y",  new Integer(1),  new Integer(1)},
                {"z",  new Integer(1),  new Integer(1)}
            },
            new String [] {
                "", "low", "up"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        marginsTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                marginsTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(marginsTable);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pl/edu/icm/visnow/lib/basic/filters/AddMargins/Bundle"); // NOI18N
        marginsTable.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("GUI.marginsTable.columnModel.title0")); // NOI18N
        marginsTable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("GUI.marginsTable.columnModel.title1")); // NOI18N
        marginsTable.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("GUI.marginsTable.columnModel.title2")); // NOI18N

        runButton.setText(bundle.getString("GUI.runButton.text")); // NOI18N
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(zeroButton);
        zeroButton.setSelected(true);
        zeroButton.setText(bundle.getString("GUI.zeroButton.text")); // NOI18N
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(fixedButton);
        fixedButton.setText(bundle.getString("GUI.fixedButton.text")); // NOI18N
        fixedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(periodicButton);
        periodicButton.setText(bundle.getString("GUI.periodicButton.text")); // NOI18N
        periodicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodicButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("GUI.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("GUI.jLabel2.text")); // NOI18N

        buttonGroup1.add(reflectedButton);
        reflectedButton.setText(bundle.getString("GUI.reflectedButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMargins)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataComponentList, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(runButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fixedButton)
                                    .addComponent(zeroButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(periodicButton)
                                    .addComponent(reflectedButton))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMargins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataComponentList, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zeroButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fixedButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(periodicButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reflectedButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(runButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runButtonActionPerformed
    {//GEN-HEADEREND:event_runButtonActionPerformed
       update();
       fireStateChanged();
    }//GEN-LAST:event_runButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zeroButtonActionPerformed
    {//GEN-HEADEREND:event_zeroButtonActionPerformed
       update();
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void fixedButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fixedButtonActionPerformed
    {//GEN-HEADEREND:event_fixedButtonActionPerformed
       update();
    }//GEN-LAST:event_fixedButtonActionPerformed

    private void periodicButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_periodicButtonActionPerformed
    {//GEN-HEADEREND:event_periodicButtonActionPerformed
       update();
    }//GEN-LAST:event_periodicButtonActionPerformed

    private void marginsTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_marginsTablePropertyChange
       update();
    }//GEN-LAST:event_marginsTablePropertyChange

    public void setField(Field in)
    {
       dataComponentList.setInField(in);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private pl.edu.icm.visnow.lib.gui.DataComponentList dataComponentList;
    private javax.swing.JRadioButton fixedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMargins;
    private javax.swing.JTable marginsTable;
    private javax.swing.JRadioButton periodicButton;
    private javax.swing.JRadioButton reflectedButton;
    private javax.swing.JButton runButton;
    private javax.swing.JRadioButton zeroButton;
    // End of variables declaration//GEN-END:variables

}
